name: build

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set up go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go

      - name: checkout
        uses: actions/checkout@v2

      - name: build and test
        run: |
          go test -timeout=60s -covermode=count -coverprofile=$GITHUB_WORKSPACE/profile.cov_tmp ./...
          cat $GITHUB_WORKSPACE/profile.cov_tmp | grep -v "mocks" > $GITHUB_WORKSPACE/profile.cov
        working-directory: app
        env:
          GOFLAGS: "-mod=vendor"
          TZ: "America/Chicago"


      - name: install golangci-lint and goveralls
        run: |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GITHUB_WORKSPACE v1.41.0
          GO111MODULE=off go get -u github.com/mattn/goveralls

      - name: run linters
        run: $GITHUB_WORKSPACE/golangci-lint run --out-format=github-actions
        working-directory: app
        env:
          GOFLAGS: "-mod=vendor"
          TZ: "America/Chicago"

      - name: submit coverage
        run: |
          export GIT_BRANCH=$GITHUB_REF
          $(go env GOPATH)/bin/goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/profile.cov
        working-directory: app
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build image
        run: docker build --build-arg CI=github .